### ISSUE TITLE
New Patch breaks mod

### ISSUE THREAD

**Issue by qualiall** [slyh/Cities2-Various-Mods#40] opened 2023-12-01 13:48 UTC
The latest game patch breaks mod.  I'm sure you are already aware, but just reporting it anyway 
error reads:
Field not found: int Game.Prefabs.ObjectRequirementElement.m_Group Due to: Could not find field in class
MissingFieldException: Field not found: int Game.Prefabs.ObjectRequirementElement.m_Group Due to: Could not find field in class
  at Game.Net.PatchedLaneSystem+UpdateLanesJob.CreateObjectLane (System.Int32 jobIndex, Unity.Mathematics.Random& random, Unity.Entities.Entity owner, Unity.Entities.Entity original, Game.Net.PatchedLaneSystem+LaneBuffer laneBuffer, Game.Objects.Transform transform, Game.Prefabs.SubLane prefabSubLane, System.Int32 laneIndex, System.Boolean sampleTerrain, System.Boolean cutForTraffic, System.Boolean isTemp, Game.Tools.Temp ownerTemp, Unity.Collections.NativeList`1[T] clearAreas) [0x00123] in <dec8ee9beb6c40d8bedc599e29ec9b76>:0 
  at Game.Net.PatchedLaneSystem+UpdateLanesJob.UpdateLanes (Unity.Entities.ArchetypeChunk chunk, System.Int32 chunkIndex) [0x0090a] in <dec8ee9beb6c40d8bedc599e29ec9b76>:0 
  at Game.Net.PatchedLaneSystem+UpdateLanesJob.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x0001c] in <dec8ee9beb6c40d8bedc599e29ec9b76>:0 
  at Game.Net.PatchedLaneSystem+UpdateLanesJob.Unity.Entities.IJobChunk.Execute (Unity.Entities.ArchetypeChunk& chunk, System.Int32 unfilteredChunkIndex, System.Boolean useEnabledMask, Unity.Burst.Intrinsics.v128& chunkEnabledMask) [0x00000] in <dec8ee9beb6c40d8bedc599e29ec9b76>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].ExecuteInternal (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x000b5] in <9a7e91fb1c0a42bdb40b67eb2c0b13bb>:0 
  at Unity.Entities.JobChunkExtensions+JobChunkProducer`1[T].Execute (Unity.Entities.JobChunkExtensions+JobChunkWrapper`1[T]& jobWrapper, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) [0x00000] in <9a7e91fb1c0a42bdb40b67eb2c0b13bb>:0 
  at (wrapper delegate-invoke) Unity.Entities.JobChunkExtensions+JobChunkProducer`1+ExecuteJobFunction[Game.Net.PatchedLaneSystem+UpdateLanesJob].invoke_void_JobChunkExtensions/JobChunkWrapper`1<T>&_intptr_intptr_JobRanges&_int(Unity.Entities.JobChunkExtensions/JobChunkWrapper`1<Game.Net.PatchedLaneSystem/UpdateLanesJob>&,intptr,intptr,Unity.Jobs.LowLevel.Unsafe.JobRanges&,int)
Colossal.Logging.CustomLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Flobesst** [comment] 2023-12-01 13:51
I have this issue too.

Not sure if it's related but my game is pausing by itself repeatedly. I had no trouble before today's patch.

**Comment by HarryBotter2333** [comment] 2023-12-01 13:52
I also encountered this problem. I had to turn off all the modules first. The bad thing is that CO does not have old version archives on steam. We cannot continue to use 1.0.13f .

**Comment by AdrianM20** [comment] 2023-12-01 13:53
I also get that error since the new update today. Cannot use the mod anymore, had to delete it.

**Comment by dmohr2** [comment] 2023-12-01 14:37
Love this mod, hope the fix is relatively easy.

**Comment by DJTSmith18** [comment] 2023-12-01 16:06
Same here, this is the most important mod I use... (at least previously done modifications are persistent even with mod disabled so my city is not completely broken)

**Comment by Forkboy2** [comment] 2023-12-01 16:09
> Not sure if it's related but my game is pausing by itself repeatedly and then crashes. I had no trouble before today's patch.

Also saw the pausing issue, although I did also have 1st person view and unlock all tiles mods installed so it might have been one of those.

**Comment by KenDaveRob** [comment] 2023-12-01 20:52
@slyh do you have a Patrion?  I would throw some money at you if you got a quick turnaround on this issue.

I don't want to go back to vanilla lights *crying inside*

**Comment by Zchulski** [comment] 2023-12-01 22:12
I can confirm this as well.  Had to delete this specific mod in order for my map to load

**Comment by slyh** [comment] 2023-12-01 23:29
I’m in the midst of working on a bug fix and therefore cannot push a small update to make it compatible with the patch. I will fix this as soon as possible. The main constraint is not financial but time.

Regarding Patreon, I’m unable to accept donations because the project relies on reverse-engineered code.

**Comment by Deanifish** [comment] 2023-12-02 00:11
> I’m in the midst of working on a bug fix and therefore cannot push a small update to make it compatible with the patch. I will fix this as soon as possible. The main constraint is not financial but time.
> 
> Regarding Patreon, I’m unable to accept donations because the project relies on reverse-engineered code.

Great to hear you're working on fixes - great mod you have here that massively helps with gameplay. 

Reckon you'd ever upload to Thunderstore for ease of keeping up to date/getting notified of when you push updates?

**Comment by slyh** [comment] 2023-12-02 11:04
Should be fixed in v0.2.3-alpha.

Regarding the Thunderstore release, it should happen very soon™.

**Closed by slyh** 2023-12-02 11:04 UTC

**Comment by wolfie35p** [comment] 2023-12-09 09:23
I'm getting this error too, but don't know what mod is causing it, and it's annoying me
