### ISSUE TITLE
Crashes latest patch of the game

### ISSUE THREAD

**Issue by Oliver123G** [slyh/Cities2-Various-Mods#45] opened 2023-12-02 00:54 UTC

**Comment by sharelj** [comment] 2023-12-02 03:59
same crashing on 1.0.15f

**Comment by ericbrownaustin** [comment] 2023-12-02 04:14
Same issue here

**Comment by adalinesimonian** [comment] 2023-12-02 06:22
Duplicate of #40

**Comment by slyh** [comment] 2023-12-02 11:04
Should be fixed in v0.2.3-alpha.

**Closed by slyh** 2023-12-02 11:04 UTC

**Comment by pikachukaki** [comment] 2023-12-02 14:39
v0.2.3-alpha working properly....
I wanna ask without opening new issue it is posible to add something similar with TPME that allow to draw in nodes so the cars obey the lines we place?
